import { Assignment, BlogCard, Course } from "./type";

export 
const demoCourses: Course[] = [
  {
    id: 1,
    title: "Experiencing Learning Landscape in Academic Boundaries",
    category: "Academic",
    className: "Class 6",
    instructor: "Dr. Sarah Ahmed",
    image:
      "https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&w=900&q=80",
    rating: 4.8,
    reviews: 24,
    price: 850,
    oldPrice: 1200,
    lessons: 18,
  },
  {
    id: 2,
    title: "Voices from the Learning Magic in Action",
    category: "Learning",
    className: "Class 7",
    instructor: "John Smith",
    image:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=900&q=80",
    rating: 4.9,
    reviews: 32,
    price: 950,
    oldPrice: 1400,
    lessons: 22,
  },
  {
    id: 3,
    title: "Boosting IQs to your Home Based Business",
    category: "Business",
    className: "Class 8",
    instructor: "Emily Watson",
    image:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=80",
    rating: 4.7,
    reviews: 19,
    price: 750,
    oldPrice: 1100,
    lessons: 15,
  },
  {
    id: 4,
    title: "Advanced Mathematics and Problem Solving",
    category: "Mathematics",
    className: "Class 6",
    instructor: "Mr. Rahim",
    image:
      "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&w=900&q=80",
    rating: 4.8,
    reviews: 28,
    price: 900,
    oldPrice: 1300,
    lessons: 20,
  },
  {
    id: 5,
    title: "English Grammar and Communication Skills",
    category: "English",
    className: "Class 7",
    instructor: "Nusrat Jahan",
    image:
      "https://images.unsplash.com/photo-1457369804613-52c61a468e7d?auto=format&fit=crop&w=900&q=80",
    rating: 4.9,
    reviews: 41,
    price: 800,
    oldPrice: 1200,
    lessons: 25,
  },
  {
    id: 6,
    title: "General Science Complete Course",
    category: "Science",
    className: "Class 8",
    instructor: "Dr. Hasan",
    image:
      "https://images.unsplash.com/photo-1532094349884-543bc11b234d?auto=format&fit=crop&w=900&q=80",
    rating: 4.6,
    reviews: 17,
    price: 700,
    oldPrice: 1000,
    lessons: 16,
  },
  {
    id: 7,
    title: "Bangla Literature and Grammar",
    category: "Bangla",
    className: "Class 9",
    instructor: "Mst. Fatema",
    image:
      "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=900&q=80",
    rating: 4.8,
    reviews: 21,
    price: 650,
    oldPrice: 950,
    lessons: 19,
  },
  {
    id: 8,
    title: "ICT Fundamentals for Students",
    category: "ICT",
    className: "Class 9",
    instructor: "Tanvir Ahmed",
    image:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&w=900&q=80",
    rating: 4.9,
    reviews: 35,
    price: 1000,
    oldPrice: 1500,
    lessons: 24,
  },
  {
    id: 9,
    title: "Higher Mathematics Preparation",
    category: "Mathematics",
    className: "Class 10",
    instructor: "Prof. Karim",
    image:
      "https://images.unsplash.com/photo-1509228468518-180dd4864904?auto=format&fit=crop&w=900&q=80",
    rating: 4.9,
    reviews: 45,
    price: 1200,
    oldPrice: 1800,
    lessons: 30,
  },
];

export const classOptions = [
  "All Classes",
  "Class 6",
  "Class 7",
  "Class 8",
  "Class 9",
  "Class 10",
];

export const assignments: Assignment[] = [
  {
    id: "#01",
    title: "About PHP",
    course: "Complete Web Development Course",
    result: "80%",
    time: "10 Minutes",
    status: "Passed",
  },
  {
    id: "#02",
    title: "JavaScript Basics",
    course: "Complete Web Development Course",
    result: "65%",
    time: "15 Minutes",
    status: "Failed",
  },
  {
    id: "#03",
    title: "React Fundamentals",
    course: "Complete Web Development Course",
    result: "90%",
    time: "12 Minutes",
    status: "Passed",
  },
  {
    id: "#04",
    title: "Node.js Introduction",
    course: "Complete Web Development Course",
    result: "—",
    time: "20 Minutes",
    status: "Pending",
  },
];


export const initialBlogs: BlogCard[] = [
  {
    id: 1,
    title: "Navigating the Job Market: Advice for Graduates",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?q=80&w=800&auto=format&fit=crop",
    date: "21",
    month: "DEC",
    author: "Admin",
    views: "1.6k",
    comments: 24,
    subject: "English",
    href: "/blog/navigating-job-market",
  },
  {
    id: 2,
    title: "The Importance of Diversity in Higher Education",
    image: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=800&auto=format&fit=crop",
    date: "21",
    month: "DEC",
    author: "Admin",
    views: "1.6k",
    comments: 24,
    subject: "Math",
    href: "/blog/importance-of-diversity",
  },
  {
    id: 3,
    title: "10 Tips for Successful Online Learning",
    image: "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?q=80&w=800&auto=format&fit=crop",
    date: "21",
    month: "DEC",
    author: "Admin",
    views: "1.6k",
    comments: 24,
    subject: "Physics",
    href: "/blog/10-tips-online-learning",
  },
];